#!/bin/bash

if [ "$(uname -s)" == "Linux" ]; then
    BASH_EXECUTABLE="/bin/bash"
else
    BASH_EXECUTABLE="/bin/bash.exe"
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <name>"
  exit 1
fi

name="$1"
permalink=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')

script_dir="$($BASH_EXECUTABLE -c 'echo $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )')"
filename="$script_dir/_wiki/${permalink}.markdown"

if [ -e "$filename" ]; then
  echo "File '$filename' already exists."
  exit 0
fi

file_content="---
layout: pagev2
title: $name
permalink: /$permalink/
---
- [Background](#background)

## Background"

if [ "$(uname -s)" != "Linux" ]; then
  file_content=$(echo -e "$file_content" | dos2unix)
fi

echo -e "$file_content" > "$filename"
echo "Wiki page '$permalink' created successfully."
